### ISSUE TITLE
Option to input lat long and adjust radius around point as boundary

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/plant-map-app#12]

**Comment by wcornwell** [comment]
this might be a new tab if the layout is too messy

**Comment by wcornwell** [comment]
thoughts on this: @tmesaglio ?

**Comment by tmesaglio** [comment]
big yes

so would we then set the circle around it as say 1km, 2km, 5km etc?

**Comment by tmesaglio** [comment]
this is the current PlantNET one
![image](https://github.com/traitecoevo/plant-map-app/assets/48739968/57afe3c1-3e58-455e-8323-bc152ccd738a)

**Comment by wcornwell** [comment]
I thought this might be easier as a new tab, but i just looked at how new tabs work in shiny and I think I may have changed my mind.  @fontikar let's discuss when you have a free moment.

**Comment by wcornwell** [comment]
i think it's working?
