### ISSUE TITLE
"soft" deploy using shinyapps.io 

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/plant-map-app#19]
We can still keep it private. i think this will be good for testing (adjusting UI) desktop and mobile! and also just good for me to learn how to do this :D 

https://shiny.posit.co/r/articles/share/shinyapps/

**Comment by wcornwell** [comment]
try out: https://rstudio.github.io/rsconnect/ ?

**Comment by fontikar** [comment]
I had a crack but the renv stuff is throwing errors with no easy way through to debugging... :( is that what you did to test the mobile version?

**Comment by fontikar** [comment]
I think it has something to do with APCalign not being on CRAN yet but can be by passed with Remotes: https://community.rstudio.com/t/using-private-github-package-with-shinyapps/97107

But does that mean I need to include a DESCRIPTION file for the app??

**Comment by fontikar** [comment]
I am happy to close this :D
