### ISSUE TITLE
spatial filters

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/plant-map-app#2]
Need to make a decision on which to include. PlantNET currently offers:

*State Forests
*National Parks (although their list also include nature reserves)
Catchment Management Areas
IBRA Regions
*Local Government areas
Botanical Subdivisions

The ones I marked with an asterisk are the ones I would personally use

**Comment by tmesaglio** [comment]
we then also have the custom KML choice

**Comment by wcornwell** [comment]
let's start with just two kmls?  which are your favorite?

**Comment by tmesaglio** [comment]
sounds good

**Comment by tmesaglio** [comment]
does an official Fowlers KML actually exist?

**Comment by tmesaglio** [comment]
Here is my Duck River KML: https://drive.google.com/file/d/1xWNEy4D8O7o-FEn2b3x6YwZUeCkwfqKj/view?usp=sharing
(it won't let me drop it here)
