### ISSUE TITLE
taxonomic filters

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/plant-map-app#3]
realistically I think family and genus are the only two ones we need, but I think there should also be the option to search for an exact species

**Comment by tmesaglio** [comment]
exact species should be free form search box

for the first two, is it possible to have a dropdown selection, but also the choice to type into that box?

**Comment by wcornwell** [comment]
this may turn out to be useful: https://stackoverflow.com/questions/35265920/auto-complete-and-selection-of-multiple-values-in-text-box-shiny

**Comment by wcornwell** [comment]
genus is done.  replaced by #10
