### ISSUE TITLE
which taxonomy do we use?

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/plant-map-app#5]
some NSW botanists will be cranky, but I think we use APC, PlantNET is way too outdate for many groups

also how do we deal with synonyms in iNat (given iNat mostly uses POWO)

**Comment by wcornwell** [comment]
right now just doing whatever ALA does, which I guess is APC

**Comment by tmesaglio** [comment]
cool makes sense

from what I can tell it's not a one to one oddly, there are some idiosyncrasies such that ALA = 99% (or whatever the number is) ALA, with some weird exceptions where they're using a different name
