### ISSUE TITLE
when clicking a hyperlink in the app, it opens two identical tabs in my internet browser (Opera)

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/plant-map-app#9]

**Comment by tmesaglio** [comment]
https://github.com/traitecoevo/plant-map-app/assets/48739968/88a28b72-d526-4a8c-900a-610510a318c2

**Comment by wcornwell** [comment]
@tmesaglio can you check if it still does this?

**Comment by fontikar** [comment]
so weird this is not reproducible for me!

**Comment by tmesaglio** [comment]
just checked, and it's now fixed!
